SELECT TOP (10) [ID]
      ,[work_item_type]
      ,[belongs_to]
      ,[title]
      ,[description]
      ,[activity]
      ,[created_date]
      ,[system_of_origin]
      ,[created_reported_by]
      ,[recorded_date]
      ,[release_number]
      ,[release_date]
      ,[notification_date]
      ,[software_version]
  FROM [cs440mw27].[dbo].[ProjectData]